import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

import { FaChartLine, FaImages, FaMedal } from 'react-icons/fa';
import { FaShop } from 'react-icons/fa6';
import Header from './Header';
import NavBar from './NavBar';
import NavBarButton from './NavBarButton';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const thaliaFont = localFont({
  src: '/Gill Sans Condensed.woff',
  variable: '--font-thalia',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${thaliaFont.variable} font-sans`}>
        <div className="flex h-screen flex-col justify-between">
          <Header />
          {children}
          <NavBar>
            <NavBarButton icon={<FaImages />} />
            <NavBarButton icon={<FaMedal />} />
            <NavBarButton icon={<FaChartLine />} />
            <NavBarButton icon={<FaShop />} />
          </NavBar>
        </div>
      </body>
    </html>
  );
}
