import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

import { FaChartLine, FaImages, FaMedal } from 'react-icons/fa';
import { FaShop } from 'react-icons/fa6';
import Header from './Header';
import NavBar from './NavBar';
import NavBarButton from './NavBarButton';

const thaliaBody = Open_Sans({ variable: '--font-body' });
const thaliaHeader = localFont({
  src: './fonts/Gill Sans Condensed.woff',
  variable: '--font-header',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${thaliaBody.variable} ${thaliaHeader.variable} font-sans`}>
        <div className="flex h-screen flex-col justify-between">
          <Header />
          {children}
          <NavBar>
            <NavBarButton icon={<FaImages />} />
            <NavBarButton icon={<FaMedal />} />
            <NavBarButton icon={<FaChartLine />} />
            <NavBarButton icon={<FaShop />} />
          </NavBar>
        </div>
      </body>
    </html>
  );
}
